version: '3.8'
services:
  pgvector_db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=${MEMGPT_PG_USER}
      - POSTGRES_PASSWORD=${MEMGPT_PG_PASSWORD}
      - POSTGRES_DB=${MEMGPT_PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  memgpt_server:
    image: memgpt/memgpt-server:0.3.7
    depends_on:
      - pgvector_db
    environment:
      - MEMGPT_PGURI=postgresql://${MEMGPT_PG_USER}:${MEMGPT_PG_PASSWORD}@pgvector_db:5432/${MEMGPT_PG_DB}
      - MEMGPT_SERVER_PASS=${MEMGPT_SERVER_PASS} # memgpt server password
      - MEMGPT_PG_DB=${MEMGPT_PG_DB}
      - MEMGPT_PG_USER=${MEMGPT_PG_USER}
      - MEMGPT_PG_PASSWORD=${MEMGPT_PG_PASSWORD}
      - MEMGPT_PG_URL=pgvector_db
    volumes:
      - ./configs/server_config.yaml:/root/.memgpt/config # config file
      - ~/.memgpt/credentials:/root/.memgpt/credentials # credentials file
    ports:
      - "8083:8083"

volumes:
  pgdata:
