site_name: MemGPT
site_url: https://memgpt.ai/
repo_url: https://github.com/cpacker/MemGPT
site_description: MemGPT documentation
nav:
  - Home: index.md
  - 'User Guide':
    - 'Quickstart': quickstart.md
    - 'Example - perpetual chatbot': example_chat.md
    - 'Example - chat with your data': example_data.md
    - 'Configuration': config.md
    - 'External data sources': data_sources.md
    - 'Changing the LLM backend': endpoints.md
    - 'FAQ': cli_faq.md
  - 'Discord Bot':
    - 'Chatting with MemGPT Bot': discord_bot.md
  - 'Local LLM':
    - 'Overview': local_llm.md
    - 'oobabooga web UI': webui.md
    - 'oobabooga web UI (on RunPod)': webui_runpod.md
    - 'LM Studio': lmstudio.md
    - 'llama.cpp': llamacpp.md
    - 'koboldcpp': koboldcpp.md
    - 'Troubleshooting': local_llm_faq.md
  - 'Advanced':
    - 'Configuring storage backends': storage.md
    - 'Supporting new LLM backends': adding_wrappers.md
    - 'Improving local LLM performance': adding_wrappers.md
    - 'Contributing to the codebase': contributing.md
theme: readthedocs
  # highlightjs: true
  # hljs_languages:
  #   - yaml
  #   - json
  #   - python
# include_homepage_in_sidebar: false
markdown_extensions:
  - admonition
